keys:
  grz_public_key_path: 'config/configs/keys/watchdog-test.pub'
  grz_private_key_path: 'config/configs/keys/watchdog-test.sec'
s3:
  endpoint_url: "http://s3service:9000"
  access_key: "Gd4G0VqhHTmi28twgsmF"
  secret: "KEx8ABzui36NhyXbiQwYXxps3HahqD7EKL54v65f"
  bucket: consented