keys:
  grz_public_key_path: 'config/keys/watchdog-test.pub'
  grz_private_key_path: 'config/keys/watchdog-test.sec'
s3:
  endpoint_url: "http://minio:9000"
  access_key: "minioadmin"
  secret: "minioadmin"
  bucket: nonconsented
