[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "grz-check-provider"
version = "0.1.0"
description = "Builds and provides the grz-check executable for grz-tools."
classifiers = [
    "Operating System :: POSIX :: Linux",
]

[tool.hatch.build.hooks.custom]
path = "hatch_hooks.py"
class = "CustomBuildHook"

[tool.hatch.build.targets.wheel]
packages = ["src/grz_check_provider"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/rust_src",
    "/hatch_hooks.py",
]

[tool.cibuildwheel]
skip = ["*-win*", "*-macos*"]
build-verbosity = 3
build-frontend = "build[uv]"
before-build = [
    "curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal",
    "source $HOME/.cargo/env",
    "cargo install cross --git https://github.com/cross-rs/cross --rev 51f46f2"
]

[dependency-groups]
dev = [
    "cibuildwheel>=3.0.0",
]
