[workspace]
authors = ["Travis Wrightsman <travis.wrightsman@uni-tuebingen.de>", "Till Hartmann <till.hartmann@bih-charite.de>"]
channels = ["conda-forge", "bioconda"]
name = "grz-watchdog"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.13.2,<10"
snakefmt = ">=0.11.2,<0.12"
#snakemake-storage-plugin-s3 = ">=0.3.6,<0.4"
#snakemake-executor-plugin-slurm = ">=1.8.0,<2"
conda = ">=25.9.0,<26"
grz-pydantic-models = ">=2.3.1,<3"
grz-db = ">=1.0.1,<2"
grzctl = ">=1.0.1,<1.1"
