$schema: "https://json-schema.org/draft/2020-12/schema"
description: "A schema for the monitor and cleanup configuration."
type: object
properties:
  monitor:
    type: object
    properties:
      interval:
        type: integer
        description: "The interval in seconds for monitoring."
    required:
      - interval
  batch:
    type: object
    properties:
      limit:
        type: integer
        description: "The batch processing limit."
    required:
      - limit
  estimates:
    type: object
    description: "Estimates of certain properties of grz-watchdog and its components"
    properties:
      speed:
        type: object
        description: "Estimates of download or processing speeds in MB/s"
        properties:
          download:
            type: integer
            minimum: 1
            default: 200
          decrypt:
            type: integer
            minimum: 1
            default: 250
          validate:
            type: integer
            minimum: 1
            default: 100
          encrypt:
            type: integer
            minimum: 1
            default: 250
          archive:
            type: integer
            minimum: 1
            default: 200
          qc:
            type: integer
            minimum 1:
              default: 10
    required:
      - speed
  temp-outputs:
    type: boolean
    description: "If true, rule outputs are temporary (marked as `temp(…)`). If false, rule outputs will be kept."
  on-failed-validation:
    type: string
    description: "Action to take on failed validation."
    enum:
      - "do-nothing"
      - "cleanup"
  auto-cleanup:
    type: string
    description: "The auto-cleanup strategy."
    enum:
      - "inbox"
      - "storage"
      - "inbox+storage"
      - "none"
  handlers:
    type: object
    description: "Custom handler code for on-start, on-error and on-success"
    properties:
      on-start:
        type: string
      on-error:
        type: string
      on-success:
        type: string
  config_paths:
    type: object
    properties:
      inbox:
        type: object
        description: "Configuration paths for inbox."
        patternProperties:
          "^[0-9]+$":
            type: object
            patternProperties:
              "^.*$":
                type: string
      archive:
        type: object
        description: "Configuration paths for archive."
        properties:
          consented:
            type: string
          nonconsented:
            type: string
        required:
          - consented
          - nonconsented
      db:
        type: string
        description: "Configuration path for the database."
      pruefbericht:
        type: string
        description: "Configuration path for the pruefbericht."
    required:
      - inbox
      - archive
      - db
      - pruefbericht
  qc:
    type: object
    properties:
      revision:
        type: string
        pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
        description: "Revision of the GRZ_QC_Workflow to use."
      selection_strategy:
        type: object
        description: ""
        properties:
          enabled:
            type: boolean
            default: true
            description: "Whether automatic qc selection is enabled or not."
          target_percentage:
            type: number
            minimum: 2.0
            maximum: 100.0
            default: 2.0
            description: "Target percentage of submissions to run QC on per LE per month."
          salt:
            type:
              - integer
              - number
              - string
            description: "Salt for random seed"
        required:
          - salt
      reference_directory:
        type: string
        default: "<resources>/references"
        description: "Path to the reference directory. Defaults to 'resources/references' (relative to the workdir)."
      prepare-qc:
        type: object
        properties:
          extra:
            type: string
            description: "A string of any additional command-line arguments for the Nextflow 'reference preparation' run."
          mode:
            type: string
            description: "Whether to create reference indices via GRZ QC Workflow or download pre-built ones"
            default: "download"
            enum:
              - "download"
              - "create"
      run-qc:
        type: object
        properties:
          extra:
            type: string
            description: "A string of any additional command-line arguments for the main Nextflow 'QC' run."
    required:
      - revision
required:
  - monitor
  - batch
  - estimates
  - on-failed-validation
  - auto-cleanup
  - config_paths
  - qc
additionalProperties: false