name: Build and Publish Binary Wheels

on:
  workflow_dispatch:
  push:
    tags:
      - 'grz-check-provider-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.0.0
        env:
          CIBW_PROJECT: packages/grz-check-provider
          CIBW_PLATFORM: linux
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_OUTPUT_DIR: wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  publish_wheels:
    name: Publish to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/grz-check-provider
    permissions:
      id-token: write

    steps:
      - name: Download all wheels from build jobs
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: dist
          merge-multiple: true

      - name: List downloaded files
        run: ls -l dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
