name: Python & Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  determine-changes:
    name: Determine Changed Packages
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }} # JSON array of objects: {"path": "...", "type": "..."}
      has_changes: ${{ steps.generate_matrix.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Get changed files within packages
        id: changed_package_files
        uses: tj-actions/changed-files@v46
        with:
          files: packages/**

      - name: List changed packages and generate matrix
        id: generate_matrix
        env:
          ALL_CHANGED_FILES: ${{ steps.changed_package_files.outputs.all_changed_files }}
        run: |
          echo "All changed files tracked by tj-actions: $ALL_CHANGED_FILES"
          directly_changed_package_dirs=()
          for file_path in $ALL_CHANGED_FILES; do
            # Extract the direct package directory (e.g., packages/package-a)
            package_dir=$(echo "$file_path" | cut -d/ -f1-2)

            # Check if it's a valid package dir (Python or Rust)
            if [[ -f "$package_dir/pyproject.toml" || -f "$package_dir/Cargo.toml" ]]; then
              if [[ ! " ${directly_changed_package_dirs[@]} " =~ " ${package_dir} " ]]; then
                directly_changed_package_dirs+=("$package_dir")
              fi
            fi
          done
          echo "Directly changed package directories: ${directly_changed_package_dirs[*]}"

          # Define dependency graph (source package name -> space-separated list of dependent package names)
          declare -A DEPENDENCY_GRAPH
          DEPENDENCY_GRAPH["grz-pydantic-models"]="grz-cli grzctl grz-common grz-db"
          DEPENDENCY_GRAPH["grz-common"]="grz-cli grzctl"
          DEPENDENCY_GRAPH["grz-db"]="grzctl"
          DEPENDENCY_GRAPH["grz-cli"]="grzctl"
          # Add other dependencies as needed: DEPENDENCY_GRAPH["pkg-x"]="pkg-y pkg-z"

          final_test_dirs=("${directly_changed_package_dirs[@]}")

          for changed_dir_path in "${directly_changed_package_dirs[@]}"; do
              pkg_name=$(basename "$changed_dir_path") # e.g., grz-cli from packages/grz-cli
              if [[ -n "${DEPENDENCY_GRAPH[$pkg_name]}" ]]; then
                  echo "Package $pkg_name changed, considering its dependents: ${DEPENDENCY_GRAPH[$pkg_name]}"
                  for dependent_name in ${DEPENDENCY_GRAPH[$pkg_name]}; do
                      dependent_path="packages/$dependent_name"
                      # Add dependent path if not already in the list
                      if [[ ! " ${final_test_dirs[@]} " =~ " ${dependent_path} " ]]; then
                          final_test_dirs+=("$dependent_path")
                          echo "Added dependent to test: $dependent_path"
                      fi
                  done
              fi
          done

          # Deduplicate final list (though the check above should prevent most duplicates)
          unique_test_dirs_array=($(echo "${final_test_dirs[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          echo "Final unique package directories to test: ${unique_test_dirs_array[*]}"

          json_objects=""
          for pkg_path in "${unique_test_dirs_array[@]}"; do
            pkg_type=""
            if [[ -f "$pkg_path/pyproject.toml" ]]; then
              pkg_type="python"
            elif [[ -f "$pkg_path/Cargo.toml" ]]; then
              pkg_type="rust"
            fi

            if [[ -n "$pkg_type" ]]; then
              json_objects+=$(jq -n --arg path "$pkg_path" --arg type "$pkg_type" '{"path": $path, "type": $type}')
            fi
          done

          matrix_json=$(echo "$json_objects" | jq -s .)

          if [ "$(echo '$matrix_json' | jq 'length')" -gt 0 ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No relevant package changes detected."
            matrix_json="[]"
          fi
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT
          echo "Generated matrix for testing: $matrix_json"

  quality-checks-python:
    name: Global Quality Checks (Python)
    runs-on: ubuntu-latest
    # Run always on PRs to main, or if determine-changes says something relevant changed on push to main.
    # This ensures quality checks run even if no "package" code changed but e.g. a workflow file did.
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.7.21'
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12 # Consistent Python for these checks

      - name: Ensure uv lockfile is up-to-date
        run: uv lock --check

      - name: Install project dev dependencies
        run: uv sync --all-extras --all-groups --all-packages

      - name: Check formatting
        run: uv run tox -e format-check

      - name: Linting
        run: uv run tox -e lints

      - name: Run type checking
        run: uv run tox -e typecheck

  quality-checks-rust:
    name: Global Quality Checks (Rust)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting for all Rust packages
        run: |
          find packages -name Cargo.toml -print0 | xargs -0 -I {} bash -c 'cd "$(dirname {})" && cargo fmt --all -- --check'

      - name: Linting with Clippy for all Rust packages
        run: |
          find packages -name Cargo.toml -print0 | xargs -0 -I {} bash -c 'cd "$(dirname {})" && cargo clippy --all-targets -- -D warnings'

  run-workspace-tests-python:
    name: Run workspace tests (Python)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.7.21'
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install project dev dependencies
        run: uv sync --all-extras --all-groups --all-packages

      - name: Test ${{ matrix.python-version }}
        run: uv run tox -e ${{ matrix.python-version }}

  test-changed-packages-python:
    name: Test Python (${{ matrix.python-version }}) - ${{ matrix.package.path }}
    needs: [determine-changes, quality-checks-python]
    if: needs.determine-changes.outputs.has_changes == 'true' && matrix.package.type == 'python'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.determine-changes.outputs.matrix) }}
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.7.21'
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install project dev dependencies
        run: uv sync --all-extras --all-groups

      - name: Extract package name from path
        id: pkg_info
        run: echo "name=$(basename ${{ matrix.package_path }})" >> $GITHUB_OUTPUT

      - name: Ensure package uv lockfile is up-to-date
        run: cd ${{ matrix.package.path }} && uv lock --check

      - name: Run tests for ${{ matrix.package.path }}
        run: cd ${{ matrix.package.path }} && uv run tox -e ${{ matrix.python-version }}

  test-changed-packages-rust:
    name: Test Rust - ${{ matrix.package.path }}
    needs: [determine-changes, quality-checks-rust]
    if: needs.determine-changes.outputs.has_changes == 'true' && matrix.package.type == 'rust'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.determine-changes.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run tests for ${{ matrix.package.path }}
        run: cd ${{ matrix.package.path }} && cargo test --all-features