name: Publish Rust Package to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'grz-check-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      # actions/checkout v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # actions/setup-python v6.2.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'
      - name: Build wheels
        # PyO3/maturin-action v1.51.0
        uses: PyO3/maturin-action@3e2bdf6ba6453a61e649744019b8a2d906c7eb38
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
          working-directory: packages/grz-check
      - name: Upload wheels
        # actions/upload-artifact v7.0.1
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: wheels-linux-${{ matrix.target }}
          path: dist

  sdist:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Build sdist
        # PyO3/maturin-action v1.51.0
        uses: PyO3/maturin-action@3e2bdf6ba6453a61e649744019b8a2d906c7eb38
        with:
          command: sdist
          args: --out dist
          working-directory: packages/grz-check
      - name: Upload sdist
      # actions/upload-artifact v7.0.1
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: wheels-sdist
          path: dist

  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    needs: [linux, sdist]
    environment:
      name: pypi
      url: https://pypi.org/p/grz-check
    permissions:
      id-token: write
      contents: read
    steps:
      # actions/download-artifact v8.0.1
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Publish to PyPI
        # pypa/gh-action-pypi-publish release/v1
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          packages-dir: dist
